spring.application.name=spring-boot-jpa-advanced

spring.datasource.url=jdbc:mysql://localhost:3306/advanced_jpa
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
