spring.application.name=spring-boot-dev-tools-actuator
server.port=8080
server.servlet.context-path=/devtoolsactuator

//management.endpoints.web.exposure.include=health,info
//management.endpoints.web.exposure.exclude=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Super Cool App
info.app.description=Demo Project for Dev Tools, Actuator
info.app.version=1.0.0

spring.security.user.name=user
spring.security.user.password=password